### PR TITLE
RST-7378 Port to release/23

### PR DESCRIPTION
**Pull request by nleblanc-lr**

### CODE REVIEW

**Review by MJohnson459 — APPROVED** [review]
Thanks! If its the same code you can just cherry-pick the original merge commit.

**Comment by nleblanc-lr** [comment]
@MJohnson459 is that not what I did? I did `git cherry-pick a9952b4bab6650912e422eb5a1e7cc86e4032f92` and that was it.

**Comment by MJohnson459** [comment]
Sorry, I meant you can just cherry pick it directly to the release branch. If its clean then you don't really need another PR

**Comment by ayrton04** [comment]
Right, once we approve a change for one branch, you can cherry-pick to others without reviews.

**Review by ayrton04 — APPROVED** [review]

**Pull request merged**
